# -*- coding: utf-8 -*-
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXcAhFSNdlLtRELZb368JO13-XW3MtPP

New model is LLM Large learning model.

we are using gemini api to to use. https://aistudio.google.com/app/apikey

api is : AIzaSyDJeYDI4qMBAYTosj34F-py4ZBWTAjofNw

for lama we have to use hugging face libery to import
"""

from google.colab import userdata
#Install the required packages
!pip install streamlit google-auth google-auth-oauthlib google-auth-httplib2 youtube-transcript-api google-generativeai

#Import the necessary Libraries
import os
from youtube_transcript_api import YouTubeTranscriptApi
import google.generativeai as genai

#configure the API key (replace "YOUR_GOOGLE_API_KEY" with your actual api key)
GOOGLE_API_KEY = userdata.get('muhammadabdullahLLM')
genai.configure(api_key=GOOGLE_API_KEY)

# Define the prompt
prompt = """You are a YouTube video summarizer. You will be taking the transcript text
and summarizing the entire video and providing the important summary in points
within 400 words. Please provide the summary of the text given here: """

# Define functions
def extract_transcript_details(youtube_video_url):
    try:
        video_id = youtube_video_url.split("=")[1]
        transcript_text = YouTubeTranscriptApi.get_transcript(video_id)
        transcript = " ".join([i["text"] for i in transcript_text])
        return transcript
    except Exception as e:
        raise e

def generate_gemini_content(transcript_text, prompt):
    model = genai.GenerativeModel("gemini-pro")
    response = model.generate_content(prompt + transcript_text)
    return response.text

# Colab input
youtube_link = input("Enter YouTube Video Link: ")

if youtube_link:
    video_id = youtube_link.split("=")[1]
    print(f"Video ID: {video_id}")

# Get the transcript and generate the summary
    transcript_text = extract_transcript_details(youtube_link)
    if transcript_text:
        summary = generate_gemini_content(transcript_text, prompt)
        print("\n## Detailed Notes:")
        print(summary)
